# SPDX-License-Identifier: TBD
hv-objs := \
    boot/main.o \
    lib/string.o \
    lib/print.o \
    common/vm/vm.o \
    common/percpu.o \
    common/io/mmio.o \
    dm/vuart.o \
    dm/console.o \
    dm/hv_shell.o

hv-includes := \
    -Ihypervisor/include \
    -Ihypervisor/common/vm \
    -Ihypervisor/dm
